// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp-Gu2VeawbXllPNPeTtzyScUEQojFH6k',
    appId: '1:16880438247:web:4cbf6891cb707b17894b42',
    messagingSenderId: '16880438247',
    projectId: 'recipeapp-fd669',
    authDomain: 'recipeapp-fd669.firebaseapp.com',
    storageBucket: 'recipeapp-fd669.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ0wBmONTV6RFesmxaotaRe_E33GXREig',
    appId: '1:16880438247:android:3d295d4c602cf207894b42',
    messagingSenderId: '16880438247',
    projectId: 'recipeapp-fd669',
    storageBucket: 'recipeapp-fd669.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsPHMAbJojDpGfY6TypWy5V54xkD8OxD0',
    appId: '1:16880438247:ios:df85a85560bfae8f894b42',
    messagingSenderId: '16880438247',
    projectId: 'recipeapp-fd669',
    storageBucket: 'recipeapp-fd669.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsPHMAbJojDpGfY6TypWy5V54xkD8OxD0',
    appId: '1:16880438247:ios:df85a85560bfae8f894b42',
    messagingSenderId: '16880438247',
    projectId: 'recipeapp-fd669',
    storageBucket: 'recipeapp-fd669.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp-Gu2VeawbXllPNPeTtzyScUEQojFH6k',
    appId: '1:16880438247:web:f9b58be3e5aa0c3e894b42',
    messagingSenderId: '16880438247',
    projectId: 'recipeapp-fd669',
    authDomain: 'recipeapp-fd669.firebaseapp.com',
    storageBucket: 'recipeapp-fd669.appspot.com',
  );

}